version: 2
jobs:
  build:
    working_directory: /${CIRCLE_PROJECT_REPONAME}
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            find .
            docker build -t ${DOCKER_USERNAME}/${CIRCLE_PROJECT_REPONAME} .
          name: Push application Docker image
          command: |
            docker login ${DOCKER_USERNAME} ${DOCKER_PASSWORD}
            docker tag ${DOCKERUSERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
            docker tag ${DOCKERUSERNAME}/${CIRCLE_PROJECT_REPONAME}:latest
            docker push ${DOCKERUSERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
            docker push ${DOCKERUSERNAME}/${CIRCLE_PROJECT_REPONAME}:latest
